langauge: generic # 언어(플랫폼) 선택

sudo: required # 관리자 권한

services: # 도커 환경 구성
    - docker

# dev 환경
before_install:
    - docker build -t karais89/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true karais89/react-test-app npm run test

# 운영환경
after_success:
    - docker build -t karais89/docker-frontend ./frontend # 각각의 이미지 빌드
    - docker build -t karais89/docker-backend ./backend
    - docker build -t karais89/docker-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin # 도커 허브에 로그인

    - docker push karais89/docker-frontend # 빌드된 이미지를 도커 허브에 푸시
    - docker push karais89/docker-backend
    - docker push karais89/docker-nginx